name: CI-CD Workflow

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd flask-app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd flask-app
          pytest test_app.py

      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-11-jre
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: Static Code Analysis
        run: |
          cd flask-app
          sonar-scanner \
          -Dsonar.projectKey=flask-sonar-argocd-k8s \
          -Dsonar.login=$SONAR_AUTH_TOKEN \
          -Dsonar.host.url=$SONAR_URL
        env:
          SONAR_URL: "http://134.33.64.163:9000"
          SONAR_AUTH_TOKEN: ${{ secrets.SONARQUBE }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd flask-app
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
        env:
          IMAGE_NAME: "ariefshaik007/ci-cd-flask-app"
          IMAGE_TAG: "${{github.run_number}}"

      - name: Update Deployment File
        run: |
          rm -rf flask-sonar-argocd-k8s
          git clone https://${{ secrets.GIT_PAT }}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git
          cd ${GIT_REPO_NAME}
          git config user.email "ariefshaik001@gmail.com"
          git config user.name "arief"
          sed -i "s/replaceImageTag/${{ github.run_number }}/g" flask-app-manifests/deployment.yml
          git add flask-app-manifests/deployment.yml
          git commit -m "Update deployment image to version ${{ github.run_number }}" || echo "No changes to commit"
          git push https://${{ secrets.GIT_PAT }}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
        env:
          GIT_REPO_NAME: "flask-sonar-argocd-k8s"
          GIT_USER_NAME: "ariefshaik7"